# .github/workflows/mkdocs.yml

name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is needed to push to the gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3 version

      - name: Install MkDocs and dependencies
        run: |
          if [ -f requirements.txt ]; then
            echo "Installing dependencies from requirements.txt"
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, installing default MkDocs and Material theme"
            pip install mkdocs mkdocs-material # Install MkDocs and mkdocs-material theme
          fi
          # If you have other plugins or themes, add them here if not in requirements.txt:
          # pip install mkdocs-awesome-pages-plugin mkdocs-mermaid2-plugin

      - name: Build MkDocs site
        run: mkdocs build --clean # Build the site, cleaning previous builds

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided token
          publish_dir: ./site # The directory where MkDocs builds the site
          # If you are using a custom domain and want to keep the CNAME file:
          # cname: example.com
          # keep_files: true # Keep existing files in the gh-pages branch (e.g., CNAME)
